import type { Metadata } from "next";
import { Footer, Header } from "../site-shell";

export const metadata: Metadata = {
  title: "Legal",
  description: "Privacy Policy, Terms of Service, and End User License Agreement for Ascend Solutions products.",
  alternates: { canonical: "/legal" },
  openGraph: { title: "Legal | Ascend Solutions", description: "Policies and agreements for Ascend Solutions products.", url: "/legal", images: ["/og.png"] },
  twitter: { title: "Legal | Ascend Solutions", description: "Policies and agreements for Ascend Solutions products.", images: ["/og.png"] },
};

const legalEmail = "mailto:legal@ascendsolutions.dev?subject=Legal%20inquiry";

function Contact({ label = "Questions?" }: { label?: string }) { return <div className="legal-contact"><p>{label}<br/><br/><strong>Ascend Solutions LLC</strong><br/>Email: <a href={legalEmail}>legal@ascendsolutions.dev</a><br/>Website: <a href="https://ascendsolutions.dev">ascendsolutions.dev</a><br/>Utah, USA</p></div>; }

export default function LegalPage(){return <><Header/><main id="main-content">
  <section className="page-hero"><div className="page-hero-shell"><span className="eyebrow">Legal</span><h1 className="page-title">Policies and agreements.</h1><p className="page-lead">Read the terms and privacy policies for Ascend Solutions products.</p></div></section>
  <div className="legal-layout"><aside className="legal-nav"><p>Legal documents</p><a href="#privacy">Privacy Policy</a><a href="#tos">Terms of Service</a><a href="#eula">EULA</a></aside><div>
    <section className="legal-doc" id="privacy"><span className="eyebrow">Legal</span><h2 className="legal-title">Privacy Policy</h2><p className="legal-meta">Effective Date: July 14, 2026 · Last Updated: October 3, 2026</p><div className="legal-intro"><strong>Our commitment:</strong> Ascend Solutions LLC builds for families. We take the privacy of your family, especially your children, seriously. We never sell your data, we minimize what we collect, and we exceed COPPA requirements for any features involving children under 13.</div>
      <h2>1. Introduction</h2><p>Welcome to Ascend Solutions LLC (&quot;Ascend Solutions,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our mobile applications and related services (collectively, the &quot;Services&quot;). By using our Services, you agree to the terms of this Privacy Policy.</p>
      <h2>2. Information We Collect</h2><h3>Information You Provide</h3><ul><li>Account registration information (name, email address, username, password)</li><li>Profile information you choose to provide</li><li>Communications you send to us</li><li>Payment information (processed securely through third-party processors)</li></ul><h3>Information Collected Automatically</h3><ul><li>Device information (device type, operating system, unique device identifiers)</li><li>Usage data (features used, time spent, actions taken within the app)</li><li>Log data (IP address, pages visited, time and date of visits)</li><li>Location data (only if you grant permission)</li><li>Crash reports and performance data</li></ul>
      <h2>3. Children&apos;s Privacy (COPPA)</h2><p>Our Services are designed for families. We do not knowingly collect personal information from children under the age of 13 without verifiable parental consent. If you are a parent or guardian and believe your child has provided us with personal information without your consent, please contact us immediately at <a href={legalEmail}>legal@ascendsolutions.dev</a>. We will take steps to remove such information promptly.</p>
      <h2>4. How We Use Your Information</h2><ul><li>Provide, operate, and maintain our Services</li><li>Improve, personalize, and expand our Services</li><li>Process transactions and send related information</li><li>Send administrative information, updates, and security alerts</li><li>Detect, prevent, and address technical issues and fraud</li><li>Comply with legal obligations</li></ul>
      <h2>5. How We Share Your Information</h2><p>We do not sell, trade, or rent your personal information to third parties. We may share your information only with trusted service providers who assist in operating our Services, when required by law, or in the event of a business transfer (with notice provided to you).</p>
      <h2>6. Your Rights</h2><ul><li><strong>Access &amp; Correction:</strong> Update your information through account settings or by contacting us</li><li><strong>Deletion:</strong> Request deletion of your data at any time</li><li><strong>California (CCPA):</strong> Right to know, delete, and opt out of sale of personal information</li><li><strong>EU/UK (GDPR):</strong> Right to access, rectify, erase, and port your data</li></ul>
      <h2>7. Contact Us</h2><Contact label="Questions about this Privacy Policy? Contact us at:"/>
      <h2>Pantrii: AI Features and Service Providers</h2>
      <p>This section applies to the Pantrii mobile app and adds to the Privacy Policy above.</p>
      <h3>AI features and OpenAI</h3>
      <p>Some Pantrii features use artificial intelligence provided by OpenAI:</p>
      <ul><li>Pantry Assistant</li><li>Receipt, shelf, and recipe photo scanning</li><li>Recipe import from a link</li><li>Voice input</li><li>Recipe scaling</li><li>Barcode product details</li></ul>
      <p>When you use one of these features, the content you provide is sent to OpenAI to process your request. Depending on the feature, this may include photos, voice recordings, recipe links, assistant messages, and pantry or grocery items related to your request.</p>
      <p>Pantrii asks for your permission the first time you use an AI feature. Nothing is sent to OpenAI through these features unless you allow it. If you decline, you can continue using Pantrii&apos;s other features.</p>
      <p>OpenAI processes this content to provide the AI features. OpenAI does not use API data to train its models by default. Under its standard API settings, OpenAI may retain content in abuse monitoring logs for up to 30 days, with longer retention where required by law or necessary to protect its services or others. Some API features may store data for longer to fulfill a request.</p>
      <h3>Other service providers</h3>
      <p>We use these providers to operate Pantrii:</p>
      <ul><li><strong>Supabase</strong> hosts account and app data, including pantry items, grocery lists, recipes, meal plans, household members, and uploaded photos.</li><li><strong>RevenueCat</strong> manages subscriptions. It receives your account ID and purchase history; Apple handles payment details for purchases made through the App Store.</li><li><strong>Resend</strong> sends account and household invitation emails.</li><li><strong>Expo</strong> delivers push notifications using your device&apos;s push token.</li><li><strong>Open Food Facts</strong> receives a product&apos;s barcode number when you scan it; we do not send your Pantrii account details with that request.</li></ul>
      <p>We do not sell your data or use it for advertising. Pantrii does not track you across other companies&apos; apps or websites.</p>
      <h3>Deleting your data</h3>
      <p>You can delete your account and its data in the app under <strong>Settings → Delete account</strong>. You can also request deletion by emailing <a href="mailto:info@ascendsolutions.dev">info@ascendsolutions.dev</a>.</p>
    </section>
    <section className="legal-doc" id="tos"><span className="eyebrow">Legal</span><h2 className="legal-title">Terms of Service</h2><p className="legal-meta">Effective Date: July 14, 2026 · Last Updated: July 14, 2026</p><div className="legal-intro">By downloading, installing, or using our Services, you confirm that you have read, understood, and agree to be bound by these Terms of Service. If you do not agree, do not use our Services.</div>
      <h2>1. Acceptance of Terms</h2><p>These Terms of Service (&quot;Terms&quot;) constitute a legally binding agreement between you and Ascend Solutions LLC governing your access to and use of our mobile applications, websites, and related services (collectively, the &quot;Services&quot;).</p>
      <h2>2. Eligibility</h2><p>You must be at least 18 years of age to create an account. If you are creating an account on behalf of a minor child, you represent that you are the parent or legal guardian and accept these Terms on their behalf.</p>
      <h2>3. Account Registration</h2><ul><li>Provide accurate, current, and complete information during registration</li><li>Keep your password secure and confidential</li><li>Notify us immediately of any unauthorized use of your account</li><li>Accept responsibility for all activities that occur under your account</li></ul>
      <h2>4. Acceptable Use</h2><p>You agree to use our Services only for lawful purposes. You agree not to impersonate others, attempt unauthorized access, interfere with the Services, upload malicious code, or use the Services to harass or harm others.</p>
      <h2>5. Intellectual Property</h2><p>The Services and all contents, including software, text, designs, images, and audio, are owned by Ascend Solutions LLC and protected by U.S. and international intellectual property laws. We grant you a limited, non-exclusive, non-transferable license to access and use the Services for personal, non-commercial use.</p>
      <h2>6. Disclaimers</h2><p>THE SERVICES ARE PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS WITHOUT WARRANTIES OF ANY KIND. ASCEND SOLUTIONS LLC DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>
      <h2>7. Limitation of Liability</h2><p>TO THE FULLEST EXTENT PERMITTED BY LAW, ASCEND SOLUTIONS LLC SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICES.</p>
      <h2>8. Governing Law</h2><p>These Terms are governed by the laws of the State of Utah, without regard to conflict of law provisions. Disputes shall be resolved through binding arbitration under American Arbitration Association rules. You waive any right to participate in class action proceedings.</p>
      <h2>9. Contact</h2><Contact label="Questions about these Terms? Contact us at:"/>
    </section>
    <section className="legal-doc" id="eula"><span className="eyebrow">Legal</span><h2 className="legal-title">End User License Agreement</h2><p className="legal-meta">Effective Date: July 14, 2026 · Last Updated: July 14, 2026</p><div className="legal-intro">This EULA is concluded between you and <strong>Ascend Solutions LLC</strong> only, not with Apple Inc. or Google LLC. Ascend Solutions LLC, not the App Store Providers, is solely responsible for the Application and its content.</div>
      <h2>1. License Grant</h2><p>Ascend Solutions LLC grants you a limited, non-exclusive, non-transferable, revocable license to download and install the Application on any Apple iOS or Android device you own or control, and to use the Application for your personal, non-commercial purposes.</p>
      <h2>2. Restrictions</h2><ul><li>Copy, modify, or distribute the Application or any portion thereof</li><li>Reverse engineer, disassemble, or attempt to derive the source code</li><li>Remove, alter, or obscure any proprietary notices</li><li>Rent, lease, sell, redistribute, or sublicense the Application</li><li>Use the Application to develop a competing product or service</li><li>Use the Application for any unlawful purpose</li></ul>
      <h2>3. Intellectual Property</h2><p>The Application and all copies are proprietary to Ascend Solutions LLC. All rights in patents, copyrights, trademarks, trade secrets, and other intellectual property rights in or associated with the Application are and will remain the property of Ascend Solutions LLC.</p>
      <h2>4. Maintenance and Support</h2><p>Ascend Solutions LLC is solely responsible for providing maintenance and support for the Application. Apple Inc. and Google LLC have no obligation to furnish maintenance or support services with respect to the Application.</p>
      <h2>5. Warranty Disclaimer</h2><p>THE APPLICATION IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTY OF ANY KIND. ASCEND SOLUTIONS LLC DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.</p>
      <h2>6. Limitation of Liability</h2><p>TO THE EXTENT NOT PROHIBITED BY LAW, ASCEND SOLUTIONS LLC SHALL NOT BE LIABLE FOR PERSONAL INJURY OR ANY INCIDENTAL, SPECIAL, INDIRECT, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE APPLICATION.</p>
      <h2>7. Third-Party Beneficiaries</h2><p>Apple Inc. and Google LLC and their subsidiaries are third-party beneficiaries of this EULA. Upon your acceptance, the App Store Providers have the right to enforce this EULA against you as third-party beneficiaries.</p>
      <h2>8. Legal Compliance</h2><p>You represent and warrant that you are not located in a country subject to a U.S. Government embargo and are not listed on any U.S. Government list of prohibited or restricted parties.</p>
      <h2>9. Governing Law</h2><p>This Agreement is governed by the laws of the State of Utah, United States. Any disputes arising under this Agreement shall be subject to the exclusive jurisdiction of the courts located in Utah.</p>
      <h2>10. Contact</h2><Contact label="Questions about this EULA? Contact us at:"/>
    </section>
  </div></div>
  </main><Footer/></>}
