import Link from "next/link";
import Image from "next/image";
import { Footer, Header } from "./site-shell";

const values = [
  ["🏡", "Family-first design", "We start with real family routines, then design technology that feels natural in the middle of a busy day."],
  ["🔒", "Privacy you can trust", "Your family’s data belongs to your family. We minimize what we collect and never sell user data."],
  ["✨", "Simple and powerful", "Useful features, clear screens, and no unnecessary steps."],
];
const founders = [["S", "Skyler", "Chief Executive Officer"], ["A", "Aaron", "Chief Financial Officer"], ["C", "Chris", "Chief Technology Officer"]];

export default function HomePage() {
  return <><Header /><main id="main-content">
    <section className="hero"><div className="hero-shell"><div><span className="eyebrow">Built for families</span><h1>Practical apps for busy <span>family life.</span></h1><p className="hero-copy">We make mobile apps that help families manage meals, errands, routines, and shared responsibilities.</p><div className="hero-actions"><Link className="button button-orange" href="/apps">Explore our apps</Link><Link className="button button-outline" href="#about">Meet the team</Link></div></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><Image className="hero-mark" src="/brand/ascend-icon.png" width={574} height={649} alt="" priority /><div className="orbit-dot one"><Image src="/brand/pantrii-light-icon.svg" width={930} height={910} alt="" /></div><div className="orbit-dot two">✓</div></div></div></section>
    <section className="section" id="values"><div className="section-shell"><div className="section-heading"><span className="eyebrow">Why Ascend</span><h2 className="section-title">We build for the way families actually live.</h2><p className="section-copy">Before we add a feature, we ask whether it would help in a real kitchen, carpool, bedtime routine, or Saturday morning grocery run.</p></div><div className="values-grid">{values.map(([icon,title,copy])=><article className="value-card" key={title}><div className="value-icon" aria-hidden="true">{icon}</div><h3 className="card-title">{title}</h3><p className="card-copy">{copy}</p></article>)}</div></div></section>
    <section className="section apps-section" id="apps"><div className="section-shell"><div className="section-heading"><span className="eyebrow">Our apps</span><h2 className="section-title">Apps for the work of family life.</h2><p className="section-copy">We focus on specific household problems and build practical tools to solve them.</p></div><div className="apps-grid"><article className="app-card featured"><Image className="app-brand-icon" src="/brand/pantrii-light-icon.svg" width={930} height={910} alt="Pantrii logo"/><h3 className="card-title">Pantrii</h3><p className="card-copy">Track food, plan meals, and keep the grocery list from turning into guesswork.</p><span className="app-status">Coming soon</span></article><article className="app-card"><span className="app-icon">🌱</span><h3 className="card-title">Kinlii</h3><p className="card-copy">Track milestones, celebrate wins, and build healthy habits as a family.</p><span className="app-status">Planned</span></article><article className="app-card"><span className="app-icon">↗</span><h3 className="card-title">Future apps</h3><p className="card-copy">We have more family tools in development.</p><span className="app-status">In planning</span></article></div></div></section>
    <section className="section" id="about"><div className="section-shell story"><div><span className="eyebrow">Our story</span><h2 className="section-title">Three founders. One shared belief.</h2><p className="section-copy">Ascend Solutions was founded by Skyler, Aaron, and Chris in Utah. We are building the kind of apps we would want in our own homes: useful, respectful of privacy, and easy to use.</p></div><div className="founder-list">{founders.map(([initial,name,role])=><div className="founder" key={name}><div className="founder-avatar">{initial}</div><div><strong>{name}</strong><span>{role}</span></div></div>)}</div></div></section>
    <section className="cta" id="contact"><div className="cta-shell"><h2 className="quote-title">Want to follow what we’re building next?</h2><a className="button button-navy" href="mailto:hello@ascendsolutions.dev">Get early access</a></div></section>
  </main><Footer /></>;
}
